### ISSUE TITLE
Integration into react-boilerplate fails

### ISSUE THREAD

**Issue by jbuck79** [chentsulin/react-redux-sweetalert#3]
Hi, I'm writing an app that uses the popular react-boilerplate as its base. I'm trying to add react-redux-sweetalert to it and it's not working for me. I was hoping that you could tell me what I'm doing wrong.  I've tried it with a clean copy of react-boilerplate and it still doesn't work, so I don't think it is caused by any of the customizations that I have made to the boilerplate.

Steps to reproduce:

1. Clone react-boilerplate master
2. run `npm setup`
3. run `yarn add react-redux-sweetalert`
4. import the css in app/app.js
5. import the reducer in app/reducers.js and add it to the combineReducers as 'sweetalert'
6. edit the following in app/containers/App/index.js
      a. add '`import ReduxSweetAlert from 'react-redux-sweetalert';`'
      b. add '`<ReduxSweetAlert />`' right after '`<Footer />`'

When browsing to the app after running `npm start`, the console shows an error 'Warning: Failed prop type: The prop `sweetalert` is marked as required in `ReduxSweetAlert`, but its value is `undefined`.' I'm guessing that error is what is causing the problem. I'm guessing there is a problem with the webpack build somewhere.

**Comment by jbuck79** [comment]
Ah, I get it now. It's because react-boilerplate uses immutablejs for its state. Any advice on how to handle this?

**Comment by chentsulin** [comment]
Hi @jbuck79, it doesn't support immutablejs now. I will look into your PR in next few days.

**Comment by jbuck79** [comment]
Thanks!

**Comment by chentsulin** [comment]
Released as https://github.com/chentsulin/react-redux-sweetalert/releases/tag/v0.2.0
